apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-16T14:56:16Z"
  name: bc4m-case
  namespace: default
  resourceVersion: "2102"
  uid: ffcc5d4f-607d-46ff-a48c-0ac653dc30f8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.15.227
  clusterIPs:
  - 10.105.15.227
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31498
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bc4m-case
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
      ipMode: VIP
