apiVersion: v1
kind: Service
metadata:
  name: bc4m-case-service
spec:
  type: LoadBalancer
  selector:
    app: bc4m-case
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs: 
    - 192.168.49.2
